# ASP.Net Core and Angular build and deploy- using templates

variables:
  buildConfiguration: 'Release'
  dotnetAppName: 'TheCrushinator.Home.Garden.API'

trigger:
  - main

stages:
  - template: azure-pipelines-build-template.yml

  - stage: DeployDEV
    displayName: 'Deploy to DEV environment'
    condition: succeeded()
    dependsOn:
      - Build_dotnet_core_app
      - Build_angular_app
    variables:
      - group: 'tc-home-dev-env-variable-group'
    jobs:
      - job: EchoVars
        steps:
          - bash: echo ${{ variables.AppServiceName }}
          - bash: echo $(AppServiceName)
          - bash: echo ${{ variables.ASPNETCOREENVIRONMENT }}
          - bash: echo $(ASPNETCOREENVIRONMENT)
          - bash: echo ${{ variables.AzureConnectionName }}
          - bash: echo $(AzureConnectionName)
          - bash: echo ${{ variables.ResourceGroupName }}
          - bash: echo $(ResourceGroupName)
      # - template: azure-pipelines-deployment-template.yml
      #   parameters:
      #     azureConnectionName: ${{ variables.AzureConnectionName }}
      #     appServiceName: ${{ variables.AppServiceName }}
      #     resourceGroupName: ${{ variables.ResourceGroupName }}
      #     environment: 'DEV'
      #     dotnetAppName: ${{ variables.dotnetAppName }}

  # - stage: DeployTEST
  #   displayName: 'Deploy to TEST environment'
  #   condition: succeeded()
  #   dependsOn:
  #     - Build_dotnet_core_app
  #     - Build_angular_app
  #   variables:
  #     - group: 'tc-home-test-env-variable-group'
  #   jobs:
  #     - template: azure-pipelines-deployment-template.yml
  #       parameters:
  #         azureConnectionName: $(AzureConnectionName)
  #         appServiceName: $(AppServiceName)
  #         resourceGroupName: $(ResourceGroupName)
  #         environment: 'TEST'
  #         dotnetAppName: $(dotnetAppName)

  # - stage: DeployPROD
  #   displayName: 'Deploy to PRD environment'
  #   condition: succeeded()
  #   dependsOn:
  #     - Build_dotnet_core_app
  #     - Build_angular_app
  #   variables:
  #     - group: 'tc-home-prd-env-variable-group'
  #   jobs:
  #     - template: azure-pipelines-deployment-template.yml
  #       parameters:
  #         azureConnectionName: $(AzureConnectionName)
  #         appServiceName: $(AppServiceName)
  #         resourceGroupName: $(ResourceGroupName)
  #         environment: 'PRD'
  #         dotnetAppName: $(dotnetAppName)
