parameters:
  - name: 'environment'
    default: ''
    type: string

  - name: 'dotnetAppName'
    default: ''
    type: string

jobs:
  - deployment: Deploy
    displayName: 'Deploy TheCrushinator Home Web App'
    environment: '${{ parameters.environment }}'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
            - bash: echo $(ResourceGroupName)
            - task: DownloadBuildArtifacts@0
              displayName: 'Download the API build artifact'
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'API'
                downloadPath: '$(System.DefaultWorkingDirectory)'

            - task: AzureWebApp@1
              displayName: Release package to Azure Web App
              inputs:
                azureSubscription: $(AzureConnectionName)
                appType: 'webAppLinux'
                appName: $(AppServiceName)
                resourceGroupName: $(ResourceGroupName)
                package: '$(System.DefaultWorkingDirectory)/**/*API*.zip'
                runtimeStack: 'DOTNET|5.0'
                startUpCommand: 'dotnet ${{ parameters.dotnetAppName }}.dll'
