parameters:
  - name: 'azureConnectionName'
    default: ''
    type: string

  - name: 'appServiceName'
    default: ''
    type: string

  - name: 'resourceGroupName'
    default: ''
    type: string

  - name: 'environment'
    default: ''
    type: string

  - name: 'dotnetAppName'
    default: ''
    type: string

jobs:
  - deployment: Deploy
    displayName: 'Deploy TheCrushinator Home Web App'
    environment: '${{ parameters.environment }}'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
            - bash: echo AppServiceName is $(AppServiceName)
            - bash: echo parameters.appServiceName is ${{ parameters.appServiceName }}
            - bash: echo AzureConnectionName is $(AzureConnectionName)
            - bash: echo parameters.azureConnectionName is ${{ parameters.azureConnectionName }}
            - bash: echo ResourceGroupName is $(ResourceGroupName)
            - bash: echo parameters.ResourceGroupName is ${{ parameters.ResourceGroupName }}
            - task: DownloadBuildArtifacts@0
              displayName: 'Download the API build artifact'
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'API'
                downloadPath: '$(System.DefaultWorkingDirectory)'

            - task: AzureWebApp@1
              displayName: Release package to Azure Web App
              inputs:
                azureSubscription: '${{ parameters.azureConnectionName }}'
                appType: 'webAppLinux'
                appName: $(AppServiceName) #'${{ parameters.appServiceName }}'
                resourceGroupName: $(ResourceGroupName) #'${{ parameters.resourceGroupName }}'
                package: '$(System.DefaultWorkingDirectory)/**/*API*.zip'
                runtimeStack: 'DOTNET|5.0'
                startUpCommand: 'dotnet ${{ parameters.dotnetAppName }}.dll'
