# ASP.Net Core and Angular build and deploy- using templates

# variables:
#   buildConfiguration: 'Release'
#   dotnetAppName:

trigger:
  - main

stages:
  - template: azure-pipelines-build-template.yml

  - stage: DeployDEV
    displayName: 'Deploy to DEV environment'
    condition: succeeded()
    dependsOn:
      - Build_dotnet_core_app
      - Build_angular_app
    variables:
      - group: 'tc-home-dev-env-variable-group'
    jobs:
      - template: azure-pipelines-deployment-template.yml
        parameters:
          environment: 'DEV'
          dotnetAppName: 'TheCrushinator.Home.Garden.API'

  # - stage: DeployTEST
  #   displayName: 'Deploy to TEST environment'
  #   condition: succeeded()
  #   dependsOn:
  #     - Build_dotnet_core_app
  #     - Build_angular_app
  #   variables:
  #     - group: 'tc-home-test-env-variable-group'
  #   jobs:
  #     - template: azure-pipelines-deployment-template.yml
  #       parameters:
  #         environment: 'TEST'
  #         dotnetAppName: $(dotnetAppName)

  # - stage: DeployPROD
  #   displayName: 'Deploy to PRD environment'
  #   condition: succeeded()
  #   dependsOn:
  #     - Build_dotnet_core_app
  #     - Build_angular_app
  #   variables:
  #     - group: 'tc-home-prd-env-variable-group'
  #   jobs:
  #     - template: azure-pipelines-deployment-template.yml
  #       parameters:
  #         environment: 'PRD'
  #         dotnetAppName: $(dotnetAppName)
