# ASP.Net Core and Angular build and deploy- using templates

trigger:
  - main

stages:
  # - template: azure-pipelines-build-template.yml

  - stage: DeployDEV
    displayName: 'Deploy to DEV environment'
    condition: succeeded()
    # dependsOn:
    #   - Build_dotnet_core_app
    #   - Build_angular_app
    variables:
      - group: 'tc-home-dev-env-variable-group'
    jobs:
      - job: EchoVars
        steps:
          - bash: echo $(AppServiceName)
          - bash: echo $(ASPNETCOREENVIRONMENT)
          - bash: echo $(AzureConnectionName)
          - bash: echo $(ResourceGroupName)
          - bash: echo ${{ variables.dotnetAppName }}
          - bash: echo AzureConnectionName is $AzureConnectionName
          - bash: echo AppServiceName is $AppServiceName
          - bash: echo ResourceGroupName is $ResourceGroupName
      - template: azure-pipelines-deployment-template.yml
        parameters:
          azureConnectionName: '${{ variables.AzureConnectionName }}'
          appServiceName: '${{ variables.AppServiceName }}'
          resourceGroupName: '${{ variables.ResourceGroupName }}'
          environment: 'DEV'
          dotnetAppName: 'TheCrushinator.Home.Garden.API'

  # - stage: DeployTEST
  #   displayName: 'Deploy to TEST environment'
  #   condition: succeeded()
  #   dependsOn:
  #     - Build_dotnet_core_app
  #     - Build_angular_app
  #   variables:
  #     - group: 'tc-home-test-env-variable-group'
  #   jobs:
  #     - template: azure-pipelines-deployment-template.yml
  #       parameters:
  #         azureConnectionName: $(AzureConnectionName)
  #         appServiceName: $(AppServiceName)
  #         resourceGroupName: $(ResourceGroupName)
  #         environment: 'TEST'
  #         dotnetAppName: $(dotnetAppName)

  # - stage: DeployPROD
  #   displayName: 'Deploy to PRD environment'
  #   condition: succeeded()
  #   dependsOn:
  #     - Build_dotnet_core_app
  #     - Build_angular_app
  #   variables:
  #     - group: 'tc-home-prd-env-variable-group'
  #   jobs:
  #     - template: azure-pipelines-deployment-template.yml
  #       parameters:
  #         azureConnectionName: $(AzureConnectionName)
  #         appServiceName: $(AppServiceName)
  #         resourceGroupName: $(ResourceGroupName)
  #         environment: 'PRD'
  #         dotnetAppName: $(dotnetAppName)
