# Deploy to production slot in Azure Web App

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Visual Studio Professional Subscription(84ca3ed4-dd88-41da-a377-b7ebb220f0ed)'
    appType: 'webAppLinux'
    appName: 'TheCrustinatorHome'
    deployToSlotOrASE: true
    resourceGroupName: 'TheCrushinator.Home'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*API*.zip'
    runtimeStack: 'DOTNET|5.0'
    startUpCommand: 'dotnet TheCrushinator.Home.Garden.API.dll'